[versions]
kotlin = "2.1.0"
okio = "3.10.2"

[libraries]
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }